server:
  port: 8081

###ThymeLeaf配置
spring:
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    content-type: text/html
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/
  # 让程序可以连接到sentinel的地址
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080 # 指向sentinel地址

feign:
# 开启feign对sentinel的支持。fallback 降级处理的开启
  sentinel:
    enabled: true
# 开启feign对hystrix的支持。fallback 降级处理的开启
#  hystrix:
#    enabled: true